[package]
name = "cachoeira_platform"
version = "0.1.0"
authors = ["Tiago Rezende <tiagosr@gmail.com>"]

[lib]
name = "cachoeira_platform"
crate-type = ["dylib"]

[dependencies]
winit = "0.14.0"
vulkano = "0.9.0"
vulkano-win = "0.9.0"
vulkano-shaders = "0.9.0"
vulkano-shader-derive = "0.9.0"